/**
 * LIGHTS OUT - F1 Knowledge & Rules Engine Data
 * Comprehensive database of F1 drivers, circuits, teams, records & telemetry
 */

export const F1_DRIVERS = [
  {
    id: "verstappen",
    name: "Max Verstappen",
    code: "VER",
    number: 1,
    team: "Red Bull Racing",
    country: "Países Bajos",
    countryCode: "NL",
    championships: 3,
    podiums: 111,
    wins: 63,
    debutYear: 2015,
    lastYear: 2026,
    points: 2980,
    poles: 40,
    gps: 208,
    helmetColor: "#ff7700",
    color: "#061389",
    stats: { speed: 99, consistency: 98, racecraft: 99, experience: 88 },
    quote: "Simply lovely, what a race!",
    funFact: "Ganó su primera carrera con Red Bull a los 18 años (GP España 2016)."
  },
  {
    id: "hamilton",
    name: "Lewis Hamilton",
    code: "HAM",
    number: 44,
    team: "Ferrari (2025) / Mercedes",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 7,
    podiums: 201,
    wins: 105,
    debutYear: 2007,
    lastYear: 2026,
    points: 4829,
    poles: 104,
    gps: 353,
    helmetColor: "#ffee00",
    color: "#00d2be",
    stats: { speed: 97, consistency: 96, racecraft: 98, experience: 99 },
    quote: "Hammer time, Bono!",
    funFact: "Comparte el récord histórico con Michael Schumacher con 7 coronas mundiales."
  },
  {
    id: "alonso",
    name: "Fernando Alonso",
    code: "ALO",
    number: 14,
    team: "Aston Martin",
    country: "España",
    countryCode: "ES",
    championships: 2,
    podiums: 106,
    wins: 32,
    debutYear: 2001,
    lastYear: 2026,
    points: 2329,
    poles: 22,
    gps: 401,
    helmetColor: "#1eff8c",
    color: "#006f62",
    stats: { speed: 95, consistency: 98, racecraft: 99, experience: 100 },
    quote: "All the time you have to leave a space!",
    funFact: "Más de 400 Grandes Premios disputados; bicampeón en 2005 y 2006."
  },
  {
    id: "leclerc",
    name: "Charles Leclerc",
    code: "LEC",
    number: 16,
    team: "Ferrari",
    country: "Mónaco",
    countryCode: "MC",
    championships: 0,
    podiums: 42,
    wins: 8,
    debutYear: 2018,
    lastYear: 2026,
    points: 1381,
    poles: 26,
    gps: 146,
    helmetColor: "#ff1801",
    color: "#e80020",
    stats: { speed: 98, consistency: 89, racecraft: 93, experience: 85 },
    quote: "I am stupid. I am stupid.",
    funFact: "Nacido en las mismas calles de Montecarlo donde logró la pole y victoria."
  },
  {
    id: "norris",
    name: "Lando Norris",
    code: "NOR",
    number: 4,
    team: "McLaren",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 0,
    podiums: 26,
    wins: 4,
    debutYear: 2019,
    lastYear: 2026,
    points: 969,
    poles: 8,
    gps: 128,
    helmetColor: "#d2ff00",
    color: "#ff8000",
    stats: { speed: 96, consistency: 92, racecraft: 92, experience: 82 },
    quote: "Scenario 7! Papaya rules!",
    funFact: "Logró su primera victoria en F1 en el GP de Miami 2024 tras 110 carreras."
  },
  {
    id: "sainz",
    name: "Carlos Sainz",
    code: "SAI",
    number: 55,
    team: "Williams (2025) / Ferrari",
    country: "España",
    countryCode: "ES",
    championships: 0,
    podiums: 25,
    wins: 4,
    debutYear: 2015,
    lastYear: 2026,
    points: 1226,
    poles: 6,
    gps: 206,
    helmetColor: "#f5d000",
    color: "#e80020",
    stats: { speed: 93, consistency: 95, racecraft: 96, experience: 89 },
    quote: "Smooth Operator...",
    funFact: "Único ganador no-Red Bull en toda la histórica temporada 2023 (Singapur)."
  },
  {
    id: "piastri",
    name: "Oscar Piastri",
    code: "PIA",
    number: 81,
    team: "McLaren",
    country: "Australia",
    countryCode: "AU",
    championships: 0,
    podiums: 10,
    wins: 2,
    debutYear: 2023,
    lastYear: 2026,
    points: 389,
    poles: 0,
    gps: 46,
    helmetColor: "#ffef33",
    color: "#ff8000",
    stats: { speed: 94, consistency: 94, racecraft: 94, experience: 75 },
    quote: "Understood. Keep pushing.",
    funFact: "Campeón consecutivo de F3 y F2 en su primer año en ambas categorías."
  },
  {
    id: "russell",
    name: "George Russell",
    code: "RUS",
    number: 63,
    team: "Mercedes",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 0,
    podiums: 15,
    wins: 3,
    debutYear: 2019,
    lastYear: 2026,
    points: 661,
    poles: 4,
    gps: 128,
    helmetColor: "#00d2be",
    color: "#00d2be",
    stats: { speed: 95, consistency: 93, racecraft: 92, experience: 84 },
    quote: "Yabba dabba doo!",
    funFact: "Conocido como 'Mr. Saturday' por sus milagrosas poles con Williams y Mercedes."
  },
  {
    id: "perez",
    name: "Sergio Pérez",
    code: "PER",
    number: 11,
    team: "Red Bull Racing",
    country: "México",
    countryCode: "MX",
    championships: 0,
    podiums: 39,
    wins: 6,
    debutYear: 2011,
    lastYear: 2026,
    points: 1637,
    poles: 3,
    gps: 281,
    helmetColor: "#00a3e0",
    color: "#061389",
    stats: { speed: 90, consistency: 88, racecraft: 95, experience: 96 },
    quote: "Checo is a legend! Absolute animal!",
    funFact: "Defensa mítica sobre Hamilton en Abu Dhabi 2021 coronando a Verstappen."
  },
  {
    id: "senna",
    name: "Ayrton Senna",
    code: "SEN",
    number: 12,
    team: "McLaren / Lotus / Williams",
    country: "Brasil",
    countryCode: "BR",
    championships: 3,
    podiums: 80,
    wins: 41,
    debutYear: 1984,
    lastYear: 1994,
    points: 614,
    poles: 65,
    gps: 161,
    helmetColor: "#ffe600",
    color: "#ffcc00",
    stats: { speed: 100, consistency: 97, racecraft: 100, experience: 95 },
    quote: "If you no longer go for a gap that exists, you are no longer a racing driver.",
    funFact: "Ganó 6 veces el Gran Premio de Mónaco, un récord vigente jamás superado."
  },
  {
    id: "schumacher",
    name: "Michael Schumacher",
    code: "MSC",
    number: 1,
    team: "Ferrari / Benetton / Mercedes",
    country: "Alemania",
    countryCode: "DE",
    championships: 7,
    podiums: 155,
    wins: 91,
    debutYear: 1991,
    lastYear: 2012,
    points: 1566,
    poles: 68,
    gps: 308,
    helmetColor: "#ff0000",
    color: "#e80020",
    stats: { speed: 99, consistency: 100, racecraft: 99, experience: 100 },
    quote: "I've always believed that you should never give up and keep fighting.",
    funFact: "Ganó 5 títulos consecutivos con Ferrari (2000 a 2004)."
  },
  {
    id: "fangio",
    name: "Juan Manuel Fangio",
    code: "FAN",
    number: 1,
    team: "Mercedes / Ferrari / Alfa Romeo / Maserati",
    country: "Argentina",
    countryCode: "AR",
    championships: 5,
    podiums: 35,
    wins: 24,
    debutYear: 1950,
    lastYear: 1958,
    points: 277,
    poles: 29,
    gps: 52,
    helmetColor: "#c2a649",
    color: "#00d2be",
    stats: { speed: 100, consistency: 99, racecraft: 100, experience: 99 },
    quote: "Hay que intentar ser el mejor, pero nunca creerse el mejor.",
    funFact: "Tiene el mayor porcentaje de victorias de la historia (46.1%) y 5 títulos con 4 marcas distintas."
  },
  {
    id: "prost",
    name: "Alain Prost",
    code: "PRO",
    number: 2,
    team: "McLaren / Williams / Ferrari / Renault",
    country: "Francia",
    countryCode: "FR",
    championships: 4,
    podiums: 106,
    wins: 51,
    debutYear: 1980,
    lastYear: 1993,
    points: 798,
    poles: 33,
    gps: 202,
    helmetColor: "#002b7f",
    color: "#ff8000",
    stats: { speed: 96, consistency: 100, racecraft: 99, experience: 98 },
    quote: "Gano carreras yendo lo más despacio posible para no romper el coche.",
    funFact: "Apodado 'El Profesor' por su cálculo milimétrico y lectura de carrera insuperable."
  },
  {
    id: "vettel",
    name: "Sebastian Vettel",
    code: "VET",
    number: 5,
    team: "Red Bull / Ferrari / Aston Martin / Toro Rosso",
    country: "Alemania",
    countryCode: "DE",
    championships: 4,
    podiums: 122,
    wins: 53,
    debutYear: 2007,
    lastYear: 2022,
    points: 3098,
    poles: 57,
    gps: 300,
    helmetColor: "#ffffff",
    color: "#061389",
    stats: { speed: 96, consistency: 95, racecraft: 95, experience: 98 },
    quote: "Ring-ding-ding-ding-ding! Grazie ragazzi!",
    funFact: "El campeón del mundo más joven de la historia de la F1 con 23 años y 134 días (2010)."
  },
  {
    id: "lauda",
    name: "Niki Lauda",
    code: "LAU",
    number: 12,
    team: "Ferrari / McLaren / Brabham / March",
    country: "Austria",
    countryCode: "AT",
    championships: 3,
    podiums: 54,
    wins: 25,
    debutYear: 1971,
    lastYear: 1985,
    points: 420,
    poles: 24,
    gps: 177,
    helmetColor: "#d90429",
    color: "#e80020",
    stats: { speed: 96, consistency: 99, racecraft: 98, experience: 97 },
    quote: "De los días de éxito no aprendes nada; del dolor y el desastre sacas conclusiones.",
    funFact: "Volvió a correr en Monza solo 42 días después de su terrorífico accidente en Nürburgring 1976."
  },
  {
    id: "stewart",
    name: "Jackie Stewart",
    code: "STE",
    number: 3,
    team: "Tyrrell / Matra / BRM",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 3,
    podiums: 43,
    wins: 27,
    debutYear: 1965,
    lastYear: 1973,
    points: 360,
    poles: 17,
    gps: 100,
    helmetColor: "#003893",
    color: "#003893",
    stats: { speed: 96, consistency: 98, racecraft: 97, experience: 96 },
    quote: "Es mejor retirarse vivo como campeón que seguir buscando récords bajo tierra.",
    funFact: "Pionero indiscutible de las medidas de seguridad modernas (casco integral, cinturones y barreras)."
  },
  {
    id: "piquet",
    name: "Nelson Piquet",
    code: "PIQ",
    number: 5,
    team: "Brabham / Williams / Benetton / Lotus",
    country: "Brasil",
    countryCode: "BR",
    championships: 3,
    podiums: 60,
    wins: 23,
    debutYear: 1978,
    lastYear: 1991,
    points: 485,
    poles: 24,
    gps: 207,
    helmetColor: "#ff0000",
    color: "#00a3e0",
    stats: { speed: 95, consistency: 93, racecraft: 96, experience: 95 },
    quote: "Prefiero ganar el campeonato con la cabeza que destrozar el motor por orgullo.",
    funFact: "Primer campeón mundial de F1 con motor turboalimentado en 1983 (Brabham-BMW)."
  },
  {
    id: "brabham",
    name: "Jack Brabham",
    code: "BRA",
    number: 1,
    team: "Brabham / Cooper",
    country: "Australia",
    countryCode: "AU",
    championships: 3,
    podiums: 31,
    wins: 14,
    debutYear: 1955,
    lastYear: 1970,
    points: 261,
    poles: 13,
    gps: 128,
    helmetColor: "#005500",
    color: "#005500",
    stats: { speed: 94, consistency: 96, racecraft: 96, experience: 98 },
    quote: "Construir tu propio coche y ganar con él es la satisfacción más grande que existe.",
    funFact: "Único piloto en la historia en ganar el Campeonato del Mundo pilotando un coche de su propia marca (1966)."
  },
  {
    id: "clark",
    name: "Jim Clark",
    code: "CLA",
    number: 1,
    team: "Lotus",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 2,
    podiums: 32,
    wins: 25,
    debutYear: 1960,
    lastYear: 1968,
    points: 274,
    poles: 33,
    gps: 73,
    helmetColor: "#004225",
    color: "#004225",
    stats: { speed: 100, consistency: 99, racecraft: 99, experience: 94 },
    quote: "Nunca conduje al límite porque nunca supe dónde estaba exactamente mi límite.",
    funFact: "Consiguió 8 Grand Chelems (pole, victoria, vuelta rápida liderando todas las vueltas), récord absoluto vigente."
  },
  {
    id: "fittipaldi",
    name: "Emerson Fittipaldi",
    code: "FIT",
    number: 1,
    team: "Lotus / McLaren / Fittipaldi",
    country: "Brasil",
    countryCode: "BR",
    championships: 2,
    podiums: 35,
    wins: 14,
    debutYear: 1970,
    lastYear: 1980,
    points: 281,
    poles: 6,
    gps: 149,
    helmetColor: "#000000",
    color: "#ff8000",
    stats: { speed: 94, consistency: 96, racecraft: 95, experience: 96 },
    quote: "La velocidad no es nada si no tienes el control absoluto en la punta de los dedos.",
    funFact: "Campeón más joven de la historia durante 33 años hasta que Fernando Alonso batió su récord en 2005."
  },
  {
    id: "hakkinen",
    name: "Mika Häkkinen",
    code: "HAK",
    number: 1,
    team: "McLaren / Lotus",
    country: "Finlandia",
    countryCode: "FI",
    championships: 2,
    podiums: 51,
    wins: 20,
    debutYear: 1991,
    lastYear: 2001,
    points: 420,
    poles: 26,
    gps: 165,
    helmetColor: "#0072ce",
    color: "#ff8000",
    stats: { speed: 98, consistency: 94, racecraft: 97, experience: 95 },
    quote: "Sisu... and yes, Michael was my greatest rival and friend.",
    funFact: "Bicampeón 1998-1999 con McLaren y protagonista del mejor adelantamiento de la historia a Schumacher en Spa 2000."
  },
  {
    id: "hill_graham",
    name: "Graham Hill",
    code: "GHI",
    number: 1,
    team: "BRM / Lotus / Brabham / Shadow",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 2,
    podiums: 36,
    wins: 14,
    debutYear: 1958,
    lastYear: 1975,
    points: 289,
    poles: 13,
    gps: 179,
    helmetColor: "#001f3f",
    color: "#001f3f",
    stats: { speed: 93, consistency: 96, racecraft: 96, experience: 98 },
    quote: "Soy un artista; la pista es mi lienzo y el coche es mi pincel.",
    funFact: "Único piloto en la historia del motor en lograr la Triple Corona (Mónaco F1, Indy 500 y 24 Horas de Le Mans)."
  },
  {
    id: "ascari",
    name: "Alberto Ascari",
    code: "ASC",
    number: 1,
    team: "Ferrari / Maserati / Lancia",
    country: "Italia",
    countryCode: "IT",
    championships: 2,
    podiums: 17,
    wins: 13,
    debutYear: 1950,
    lastYear: 1955,
    points: 140,
    poles: 14,
    gps: 33,
    helmetColor: "#0080ff",
    color: "#e80020",
    stats: { speed: 98, consistency: 97, racecraft: 97, experience: 93 },
    quote: "Cuando lidero desde la pole, nadie puede atraparme.",
    funFact: "Primer bicampeón de Ferrari (1952 y 1953) con 7 victorias consecutivas en una misma temporada."
  },
  {
    id: "raikkonen",
    name: "Kimi Räikkönen",
    code: "RAI",
    number: 7,
    team: "Ferrari / McLaren / Lotus / Alfa Romeo / Sauber",
    country: "Finlandia",
    countryCode: "FI",
    championships: 1,
    podiums: 103,
    wins: 21,
    debutYear: 2001,
    lastYear: 2021,
    points: 1873,
    poles: 18,
    gps: 353,
    helmetColor: "#ff0000",
    color: "#e80020",
    stats: { speed: 97, consistency: 94, racecraft: 96, experience: 100 },
    quote: "Leave me alone, I know what to do!",
    funFact: "Último piloto en ser Campeón del Mundo con Scuderia Ferrari (2007) y más de 349 GGPP disputados."
  },
  {
    id: "mansell",
    name: "Nigel Mansell",
    code: "MAN",
    number: 5,
    team: "Williams / Ferrari / Lotus / McLaren",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 1,
    podiums: 59,
    wins: 31,
    debutYear: 1980,
    lastYear: 1995,
    points: 482,
    poles: 32,
    gps: 191,
    helmetColor: "#002060",
    color: "#00a3e0",
    stats: { speed: 97, consistency: 91, racecraft: 99, experience: 96 },
    quote: "Si no lo dejas todo en el asfalto, no mereces sentarte en un coche de carreras.",
    funFact: "Conocido como 'Il Leone'; campeón arrollador en 1992 con el mítico Williams FW14B de suspensión activa."
  },
  {
    id: "rosberg_nico",
    name: "Nico Rosberg",
    code: "ROS",
    number: 6,
    team: "Mercedes / Williams",
    country: "Alemania",
    countryCode: "DE",
    championships: 1,
    podiums: 57,
    wins: 23,
    debutYear: 2006,
    lastYear: 2016,
    points: 1594,
    poles: 30,
    gps: 206,
    helmetColor: "#00e5ff",
    color: "#00d2be",
    stats: { speed: 94, consistency: 96, racecraft: 94, experience: 94 },
    quote: "Lo di absolutamente todo física y psicológicamente contra Lewis.",
    funFact: "Hijo de Keke Rosberg; se coronó campeón en 2016 en Abu Dhabi y anunció su retirada 5 días después."
  },
  {
    id: "button",
    name: "Jenson Button",
    code: "BUT",
    number: 22,
    team: "Brawn GP / McLaren / BAR / Honda / Benetton / Williams",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 1,
    podiums: 50,
    wins: 15,
    debutYear: 2000,
    lastYear: 2017,
    points: 1235,
    poles: 8,
    gps: 309,
    helmetColor: "#ffffff",
    color: "#00d2be",
    stats: { speed: 93, consistency: 97, racecraft: 96, experience: 98 },
    quote: "We're World Champions! Oh yes, baby!",
    funFact: "Campeón del Mundo con Brawn GP en 2009 y maestro indiscutible bajo lluvia cambiante (Canadá 2011)."
  },
  {
    id: "hunt",
    name: "James Hunt",
    code: "HUN",
    number: 11,
    team: "McLaren / Hesketh / Wolf",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 1,
    podiums: 23,
    wins: 10,
    debutYear: 1973,
    lastYear: 1979,
    points: 179,
    poles: 14,
    gps: 93,
    helmetColor: "#000000",
    color: "#ff8000",
    stats: { speed: 95, consistency: 88, racecraft: 95, experience: 91 },
    quote: "Sex: Breakfast of Champions.",
    funFact: "Campeón en 1976 en Fuji bajo lluvia torrencial tras la legendaria rivalidad con Niki Lauda."
  },
  {
    id: "andretti",
    name: "Mario Andretti",
    code: "AND",
    number: 5,
    team: "Lotus / Ferrari / Alfa Romeo / March",
    country: "Estados Unidos",
    countryCode: "US",
    championships: 1,
    podiums: 19,
    wins: 12,
    debutYear: 1968,
    lastYear: 1982,
    points: 180,
    poles: 18,
    gps: 131,
    helmetColor: "#c0c0c0",
    color: "#004225",
    stats: { speed: 96, consistency: 95, racecraft: 97, experience: 98 },
    quote: "Si todo parece bajo control, es que no estás yendo lo suficientemente rápido.",
    funFact: "Último estadounidense en ganar el título mundial de F1 (1978 con el Lotus 79 de efecto suelo)."
  },
  {
    id: "villeneuve_jacques",
    name: "Jacques Villeneuve",
    code: "VIL",
    number: 3,
    team: "Williams / BAR / Sauber / Renault / BAR",
    country: "Canadá",
    countryCode: "CA",
    championships: 1,
    podiums: 23,
    wins: 11,
    debutYear: 1996,
    lastYear: 2006,
    points: 235,
    poles: 13,
    gps: 165,
    helmetColor: "#ff007f",
    color: "#00a3e0",
    stats: { speed: 94, consistency: 91, racecraft: 95, experience: 93 },
    quote: "Corro para divertirme y ser el más rápido, no para hacer amigos.",
    funFact: "Campeón del Mundo en 1997 en Jerez tras el famoso toque con Michael Schumacher."
  },
  {
    id: "hill_damon",
    name: "Damon Hill",
    code: "DHI",
    number: 0,
    team: "Williams / Jordan / Arrows / Brabham",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 1,
    podiums: 42,
    wins: 22,
    debutYear: 1992,
    lastYear: 1999,
    points: 360,
    poles: 20,
    gps: 122,
    helmetColor: "#001f3f",
    color: "#00a3e0",
    stats: { speed: 94, consistency: 94, racecraft: 94, experience: 94 },
    quote: "Hijo de un campeón y campeón yo mismo. El círculo está completo.",
    funFact: "Primer hijo de un campeón mundial (Graham Hill) en proclamarse también Campeón del Mundo (1996)."
  },
  {
    id: "surtees",
    name: "John Surtees",
    code: "SUR",
    number: 1,
    team: "Ferrari / Honda / Cooper / Surtees",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 1,
    podiums: 24,
    wins: 6,
    debutYear: 1960,
    lastYear: 1972,
    points: 180,
    poles: 8,
    gps: 113,
    helmetColor: "#004080",
    color: "#e80020",
    stats: { speed: 95, consistency: 93, racecraft: 97, experience: 96 },
    quote: "Las dos y las cuatro ruedas requieren la misma sensibilidad y valentía.",
    funFact: "Único ser humano en ser Campeón del Mundo de Motociclismo (500cc) y Campeón del Mundo de F1 (1964)."
  },
  {
    id: "rindt",
    name: "Jochen Rindt",
    code: "RIN",
    number: 22,
    team: "Lotus / Cooper / Brabham",
    country: "Austria",
    countryCode: "AT",
    championships: 1,
    podiums: 13,
    wins: 6,
    debutYear: 1964,
    lastYear: 1970,
    points: 109,
    poles: 10,
    gps: 62,
    helmetColor: "#ffffff",
    color: "#004225",
    stats: { speed: 97, consistency: 92, racecraft: 98, experience: 91 },
    quote: "En un Lotus, o eres campeón del mundo o estás muerto.",
    funFact: "Único campeón póstumo de la historia de la F1 (coronado en 1970 tras fallecer en Monza)."
  },
  {
    id: "jones",
    name: "Alan Jones",
    code: "JON",
    number: 27,
    team: "Williams / Shadow / Lola / Arrows",
    country: "Australia",
    countryCode: "AU",
    championships: 1,
    podiums: 24,
    wins: 12,
    debutYear: 1975,
    lastYear: 1986,
    points: 206,
    poles: 6,
    gps: 117,
    helmetColor: "#ff0000",
    color: "#00a3e0",
    stats: { speed: 94, consistency: 93, racecraft: 96, experience: 94 },
    quote: "Si te metes por el interior, prepárate para no salir ileso.",
    funFact: "Otorgó el primer título mundial de constructores y de pilotos a Frank Williams en 1980."
  },
  {
    id: "rosberg_keke",
    name: "Keke Rosberg",
    code: "KRO",
    number: 6,
    team: "Williams / McLaren / ATS / Fittipaldi",
    country: "Finlandia",
    countryCode: "FI",
    championships: 1,
    podiums: 17,
    wins: 5,
    debutYear: 1978,
    lastYear: 1986,
    points: 159,
    poles: 5,
    gps: 128,
    helmetColor: "#003399",
    color: "#00a3e0",
    stats: { speed: 95, consistency: 90, racecraft: 97, experience: 93 },
    quote: "Conducir al límite es la única forma en que sé acelerar.",
    funFact: "Campeón del Mundo en 1982 ganando solo una única carrera en toda la temporada."
  },
  {
    id: "scheckter",
    name: "Jody Scheckter",
    code: "SCH",
    number: 11,
    team: "Ferrari / Tyrrell / McLaren / Wolf",
    country: "Sudáfrica",
    countryCode: "ZA",
    championships: 1,
    podiums: 33,
    wins: 10,
    debutYear: 1972,
    lastYear: 1980,
    points: 255,
    poles: 3,
    gps: 113,
    helmetColor: "#ffffff",
    color: "#e80020",
    stats: { speed: 94, consistency: 95, racecraft: 95, experience: 94 },
    quote: "El respeto entre pilotos en mi época era una cuestión de supervivencia.",
    funFact: "Único campeón del mundo del continente africano (1979 con Ferrari antes de la sequía de 21 años)."
  },
  {
    id: "denny_hulme",
    name: "Denny Hulme",
    code: "HUL",
    number: 2,
    team: "Brabham / McLaren",
    country: "Nueva Zelanda",
    countryCode: "NZ",
    championships: 1,
    podiums: 33,
    wins: 8,
    debutYear: 1965,
    lastYear: 1974,
    points: 248,
    poles: 1,
    gps: 112,
    helmetColor: "#ffd700",
    color: "#ff8000",
    stats: { speed: 93, consistency: 96, racecraft: 94, experience: 95 },
    quote: "El oso corre en silencio y habla en el podio.",
    funFact: "Campeón en 1967 apodado 'El Oso' y cofundador del poderío de Bruce McLaren en Can-Am."
  },
  {
    id: "phil_hill",
    name: "Phil Hill",
    code: "PHI",
    number: 2,
    team: "Ferrari / Cooper / ATS / Porsche",
    country: "Estados Unidos",
    countryCode: "US",
    championships: 1,
    podiums: 16,
    wins: 3,
    debutYear: 1958,
    lastYear: 1964,
    points: 98,
    poles: 6,
    gps: 52,
    helmetColor: "#ffffff",
    color: "#e80020",
    stats: { speed: 93, consistency: 94, racecraft: 93, experience: 94 },
    quote: "Naciste para competir cuando la velocidad calma tus dudas.",
    funFact: "Primer estadounidense en coronarse Campeón del Mundo de Fórmula 1 (1961 con Ferrari)."
  },
  {
    id: "hawthorn",
    name: "Mike Hawthorn",
    code: "HAW",
    number: 6,
    team: "Ferrari / Vanwall / BRM / Cooper",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 1,
    podiums: 16,
    wins: 3,
    debutYear: 1952,
    lastYear: 1958,
    points: 127,
    poles: 4,
    gps: 47,
    helmetColor: "#ffffff",
    color: "#e80020",
    stats: { speed: 92, consistency: 94, racecraft: 92, experience: 91 },
    quote: "La pajarita y la gorra plana son mi seña de identidad en la parrilla.",
    funFact: "Primer campeón mundial británico de la historia (1958 con Ferrari)."
  },
  {
    id: "farina",
    name: "Giuseppe Farina",
    code: "FAR",
    number: 1,
    team: "Alfa Romeo / Ferrari / Maserati",
    country: "Italia",
    countryCode: "IT",
    championships: 1,
    podiums: 20,
    wins: 5,
    debutYear: 1950,
    lastYear: 1955,
    points: 127,
    poles: 5,
    gps: 34,
    helmetColor: "#000080",
    color: "#990000",
    stats: { speed: 94, consistency: 92, racecraft: 95, experience: 95 },
    quote: "Un hombre que no arriesga la vida no sabe qué significa vivir.",
    funFact: "El primer campeón de la historia de la Fórmula 1 en 1950 con el Alfa Romeo 158."
  },
  {
    id: "ricciardo",
    name: "Daniel Ricciardo",
    code: "RIC",
    number: 3,
    team: "Red Bull / McLaren / Renault / Toro Rosso / RB",
    country: "Australia",
    countryCode: "AU",
    championships: 0,
    podiums: 32,
    wins: 8,
    debutYear: 2011,
    lastYear: 2024,
    points: 1329,
    poles: 3,
    gps: 258,
    helmetColor: "#00e1ff",
    color: "#061389",
    stats: { speed: 92, consistency: 89, racecraft: 96, experience: 97 },
    quote: "I never left. Honey Badger mode!",
    funFact: "El rey de la frenada tardía ('divebomb') y creador de la celebración del 'Shoey'."
  },
  {
    id: "bottas",
    name: "Valtteri Bottas",
    code: "BOT",
    number: 77,
    team: "Mercedes / Williams / Sauber / Alfa Romeo",
    country: "Finlandia",
    countryCode: "FI",
    championships: 0,
    podiums: 67,
    wins: 10,
    debutYear: 2013,
    lastYear: 2026,
    points: 1797,
    poles: 20,
    gps: 244,
    helmetColor: "#00d2be",
    color: "#00d2be",
    stats: { speed: 93, consistency: 94, racecraft: 90, experience: 97 },
    quote: "To whom it may concern... fuck you!",
    funFact: "Clave en 5 títulos de constructores consecutivos de Mercedes (2017 a 2021)."
  },
  {
    id: "barrichello",
    name: "Rubens Barrichello",
    code: "BAR",
    number: 2,
    team: "Ferrari / Brawn GP / Jordan / Stewart / Williams",
    country: "Brasil",
    countryCode: "BR",
    championships: 0,
    podiums: 68,
    wins: 11,
    debutYear: 1993,
    lastYear: 2011,
    points: 658,
    poles: 14,
    gps: 326,
    helmetColor: "#ff7700",
    color: "#e80020",
    stats: { speed: 92, consistency: 95, racecraft: 93, experience: 100 },
    quote: "Amo este deporte más que a nada en el mundo.",
    funFact: "Disputó 322 Grandes Premios y fue subcampeón mundial en 2002 y 2004 junto a Schumacher."
  },
  {
    id: "massa",
    name: "Felipe Massa",
    code: "MAS",
    number: 19,
    team: "Ferrari / Williams / Sauber",
    country: "Brasil",
    countryCode: "BR",
    championships: 0,
    podiums: 41,
    wins: 11,
    debutYear: 2002,
    lastYear: 2017,
    points: 1167,
    poles: 16,
    gps: 272,
    helmetColor: "#009933",
    color: "#e80020",
    stats: { speed: 92, consistency: 90, racecraft: 92, experience: 97 },
    quote: "Fui campeón del mundo durante 30 segundos en Interlagos 2008.",
    funFact: "Subcampeón en 2008 por un solo punto tras adelantar Hamilton a Glock en la última curva."
  },
  {
    id: "webber",
    name: "Mark Webber",
    code: "WEB",
    number: 2,
    team: "Red Bull / Williams / Jaguar / Minardi",
    country: "Australia",
    countryCode: "AU",
    championships: 0,
    podiums: 42,
    wins: 9,
    debutYear: 2002,
    lastYear: 2013,
    points: 1047,
    poles: 13,
    gps: 217,
    helmetColor: "#ffe600",
    color: "#061389",
    stats: { speed: 92, consistency: 92, racecraft: 93, experience: 96 },
    quote: "Not bad for a number two driver!",
    funFact: "Ganó 2 veces el prestigioso GP de Mónaco (2010 y 2012) con Red Bull."
  },
  {
    id: "montoya",
    name: "Juan Pablo Montoya",
    code: "MON",
    number: 3,
    team: "Williams / McLaren",
    country: "Colombia",
    countryCode: "CO",
    championships: 0,
    podiums: 30,
    wins: 7,
    debutYear: 2001,
    lastYear: 2006,
    points: 307,
    poles: 13,
    gps: 95,
    helmetColor: "#fcd116",
    color: "#00a3e0",
    stats: { speed: 97, consistency: 87, racecraft: 98, experience: 90 },
    quote: "You broke my fucking head!",
    funFact: "Poseedor de la vuelta más rápida de la historia en Monza a más de 262 km/h de media durante años."
  },
  {
    id: "coulthard",
    name: "David Coulthard",
    code: "COU",
    number: 4,
    team: "McLaren / Williams / Red Bull",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 0,
    podiums: 62,
    wins: 13,
    debutYear: 1994,
    lastYear: 2008,
    points: 535,
    poles: 12,
    gps: 247,
    helmetColor: "#003366",
    color: "#ff8000",
    stats: { speed: 92, consistency: 94, racecraft: 92, experience: 98 },
    quote: "Consistencia es la clave de permanecer 15 años en la cima.",
    funFact: "Subcampeón en 2001 y otorgó a Red Bull el primer podio de su historia en Mónaco 2006."
  },
  {
    id: "gilles_villeneuve",
    name: "Gilles Villeneuve",
    code: "GVIL",
    number: 27,
    team: "Ferrari / McLaren",
    country: "Canadá",
    countryCode: "CA",
    championships: 0,
    podiums: 13,
    wins: 6,
    debutYear: 1977,
    lastYear: 1982,
    points: 107,
    poles: 2,
    gps: 68,
    helmetColor: "#ff0000",
    color: "#e80020",
    stats: { speed: 99, consistency: 85, racecraft: 100, experience: 88 },
    quote: "Conducir al 110% en cada curva es la única manera que conozco de estar vivo.",
    funFact: "El duelo rueda a rueda con René Arnoux en Dijon 1979 sigue considerándose el más épico de la historia."
  },
  {
    id: "moss",
    name: "Stirling Moss",
    code: "MOS",
    number: 7,
    team: "Mercedes / Maserati / Vanwall / Lotus / Rob Walker",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 0,
    podiums: 24,
    wins: 16,
    debutYear: 1951,
    lastYear: 1961,
    points: 186,
    poles: 16,
    gps: 67,
    helmetColor: "#ffffff",
    color: "#00d2be",
    stats: { speed: 98, consistency: 95, racecraft: 98, experience: 97 },
    quote: "Mejor perder con honor que ganar con trampa.",
    funFact: "El 'Campeón sin Corona'; cuatro veces subcampeón del mundo y ganador de las Mille Miglia."
  },
  {
    id: "peterson",
    name: "Ronnie Peterson",
    code: "PET",
    number: 6,
    team: "Lotus / March / Tyrrell",
    country: "Suecia",
    countryCode: "SE",
    championships: 0,
    podiums: 26,
    wins: 10,
    debutYear: 1970,
    lastYear: 1978,
    points: 206,
    poles: 14,
    gps: 123,
    helmetColor: "#0000ff",
    color: "#004225",
    stats: { speed: 98, consistency: 88, racecraft: 98, experience: 92 },
    quote: "El rey del derrape controlado en la época dorada de Lotus.",
    funFact: "Subcampeón del mundo en 1971 y 1978, considerado uno de los pilotos de derrape más veloces."
  },
  {
    id: "gasly",
    name: "Pierre Gasly",
    code: "GAS",
    number: 10,
    team: "Alpine / AlphaTauri / Red Bull / Toro Rosso",
    country: "Francia",
    countryCode: "FR",
    championships: 0,
    podiums: 5,
    wins: 1,
    debutYear: 2017,
    lastYear: 2026,
    points: 418,
    poles: 0,
    gps: 151,
    helmetColor: "#e60000",
    color: "#0078c1",
    stats: { speed: 90, consistency: 90, racecraft: 91, experience: 87 },
    quote: "WHAT DID WE JUST DO?!",
    funFact: "Victoria histórica en Monza 2020 con AlphaTauri resistiendo los ataques de Carlos Sainz."
  },
  {
    id: "ocon",
    name: "Esteban Ocon",
    code: "OCO",
    number: 31,
    team: "Haas (2025) / Alpine / Force India / Manor",
    country: "Francia",
    countryCode: "FR",
    championships: 0,
    podiums: 4,
    wins: 1,
    debutYear: 2016,
    lastYear: 2026,
    points: 445,
    poles: 0,
    gps: 154,
    helmetColor: "#ff007f",
    color: "#0078c1",
    stats: { speed: 89, consistency: 91, racecraft: 92, experience: 89 },
    quote: "Never give up, hard work pays off.",
    funFact: "Victoria milagrosa en el GP de Hungría 2021 tras una caótica salida sobre asfalto mojado."
  },
  {
    id: "tsunoda",
    name: "Yuki Tsunoda",
    code: "TSU",
    number: 22,
    team: "RB / AlphaTauri",
    country: "Japón",
    countryCode: "JP",
    championships: 0,
    podiums: 0,
    wins: 0,
    debutYear: 2021,
    lastYear: 2026,
    points: 89,
    poles: 0,
    gps: 87,
    helmetColor: "#ff4d00",
    color: "#061389",
    stats: { speed: 89, consistency: 88, racecraft: 89, experience: 84 },
    quote: "Traffic paradise! Let me drive!",
    funFact: "El piloto japonés más consistente de la era turbo híbrida, criado en la academia Honda."
  },
  {
    id: "albon",
    name: "Alexander Albon",
    code: "ALB",
    number: 23,
    team: "Williams / Red Bull / Toro Rosso",
    country: "Tailandia",
    countryCode: "TH",
    championships: 0,
    podiums: 2,
    wins: 0,
    debutYear: 2019,
    lastYear: 2026,
    points: 240,
    poles: 0,
    gps: 102,
    helmetColor: "#0033cc",
    color: "#00a3e0",
    stats: { speed: 91, consistency: 92, racecraft: 92, experience: 86 },
    quote: "They race me so hard!",
    funFact: "Primer piloto de bandera tailandesa en subir a un podio de F1 (Mugello 2020 con Red Bull)."
  },
  {
    id: "hulkenberg",
    name: "Nico Hülkenberg",
    code: "HUL",
    number: 27,
    team: "Sauber (2025) / Haas / Renault / Force India / Williams",
    country: "Alemania",
    countryCode: "DE",
    championships: 0,
    podiums: 0,
    wins: 0,
    debutYear: 2010,
    lastYear: 2026,
    points: 561,
    poles: 1,
    gps: 227,
    helmetColor: "#33ff00",
    color: "#ffffff",
    stats: { speed: 92, consistency: 93, racecraft: 91, experience: 96 },
    quote: "HUUUULKENBACK!",
    funFact: "Posee una pole histórica en Brasil 2010 y más de 220 GGPP con ritmo descomunal en clasificación."
  },
  {
    id: "magnussen",
    name: "Kevin Magnussen",
    code: "MAG",
    number: 20,
    team: "Haas / Renault / McLaren",
    country: "Dinamarca",
    countryCode: "DK",
    championships: 0,
    podiums: 1,
    wins: 0,
    debutYear: 2014,
    lastYear: 2026,
    points: 200,
    poles: 1,
    gps: 182,
    helmetColor: "#cc0000",
    color: "#ffffff",
    stats: { speed: 89, consistency: 87, racecraft: 94, experience: 92 },
    quote: "Suck my balls, mate!",
    funFact: "Podio en su debut en Australia 2014 con McLaren y pole heroica con Haas en Brasil 2022."
  },
  {
    id: "kubica",
    name: "Robert Kubica",
    code: "KUB",
    number: 88,
    team: "BMW Sauber / Renault / Williams / Alfa Romeo",
    country: "Polonia",
    countryCode: "PL",
    championships: 0,
    podiums: 12,
    wins: 1,
    debutYear: 2006,
    lastYear: 2021,
    points: 274,
    poles: 1,
    gps: 99,
    helmetColor: "#dc143c",
    color: "#003399",
    stats: { speed: 94, consistency: 92, racecraft: 95, experience: 91 },
    quote: "El talento puro nunca desaparece a pesar de las cicatrices.",
    funFact: "Ganó el GP de Canadá 2008 un año después de sobrevivir a un brutal impacto a más de 300 km/h allí mismo."
  },
  {
    id: "stroll",
    name: "Lance Stroll",
    code: "STR",
    number: 18,
    team: "Aston Martin / Racing Point / Williams",
    country: "Canadá",
    countryCode: "CA",
    championships: 0,
    podiums: 3,
    wins: 0,
    debutYear: 2017,
    lastYear: 2026,
    points: 292,
    poles: 1,
    gps: 164,
    helmetColor: "#00ff66",
    color: "#006f62",
    stats: { speed: 88, consistency: 85, racecraft: 88, experience: 88 },
    quote: "What happened? We need to know!",
    funFact: "Podio en Bakú 2017 a los 18 años y pole position sobre asfalto empapado en Turquía 2020."
  },
  {
    id: "colapinto",
    name: "Franco Colapinto",
    code: "COL",
    number: 43,
    team: "Williams Racing (2024-2025)",
    country: "Argentina",
    countryCode: "AR",
    championships: 0,
    podiums: 0,
    wins: 0,
    debutYear: 2024,
    lastYear: 2026,
    points: 5,
    poles: 0,
    gps: 9,
    helmetColor: "#0099ff",
    color: "#00a3e0",
    stats: { speed: 90, consistency: 88, racecraft: 91, experience: 75 },
    quote: "¡Vamos Argentina carajo!",
    funFact: "Primer argentino en sumar puntos en F1 en más de 40 años tras deslumbrar en Bakú y Singapur 2024."
  },
  {
    id: "bearman",
    name: "Oliver Bearman",
    code: "BEA",
    number: 87,
    team: "Haas (2025) / Ferrari",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 0,
    podiums: 0,
    wins: 0,
    debutYear: 2024,
    lastYear: 2026,
    points: 7,
    poles: 0,
    gps: 3,
    helmetColor: "#ffcc00",
    color: "#e80020",
    stats: { speed: 90, consistency: 89, racecraft: 90, experience: 74 },
    quote: "Dream debut with the Scuderia in Jeddah!",
    funFact: "Sustituyó a Carlos Sainz en Yeda 2024 de imprevisto y puntuó en 7ª posición con tan solo 18 años."
  },
  {
    id: "antonelli",
    name: "Kimi Antonelli",
    code: "ANT",
    number: 12,
    team: "Mercedes-AMG (2025)",
    country: "Italia",
    countryCode: "IT",
    championships: 0,
    podiums: 0,
    wins: 0,
    debutYear: 2025,
    lastYear: 2026,
    points: 0,
    poles: 0,
    gps: 1,
    helmetColor: "#00d2be",
    color: "#00d2be",
    stats: { speed: 93, consistency: 88, racecraft: 91, experience: 72 },
    quote: "The next generation of the Silver Arrows.",
    funFact: "El prodigio italiano fichado por Mercedes para ocupar el asiento de Lewis Hamilton en 2025."
  },
  {
    id: "zhou",
    name: "Zhou Guanyu",
    code: "ZHO",
    number: 24,
    team: "Kick Sauber / Alfa Romeo",
    country: "China",
    countryCode: "CN",
    championships: 0,
    podiums: 0,
    wins: 0,
    debutYear: 2022,
    lastYear: 2026,
    points: 12,
    poles: 0,
    gps: 66,
    helmetColor: "#990033",
    color: "#52e252",
    stats: { speed: 87, consistency: 89, racecraft: 88, experience: 82 },
    quote: "Making history for my country in Formula 1.",
    funFact: "Primer piloto oficial de la República Popular China en competir en la Fórmula 1 y puntuar en su debut (Baréin 2022)."
  },
  {
    id: "sargeant",
    name: "Logan Sargeant",
    code: "SAR",
    number: 2,
    team: "Williams Racing",
    country: "Estados Unidos",
    countryCode: "US",
    championships: 0,
    podiums: 0,
    wins: 0,
    debutYear: 2023,
    lastYear: 2024,
    points: 1,
    poles: 0,
    gps: 37,
    helmetColor: "#002b7f",
    color: "#00a3e0",
    stats: { speed: 85, consistency: 83, racecraft: 84, experience: 76 },
    quote: "Points on home soil in Austin!",
    funFact: "Primer estadounidense en sumar un punto en F1 en 30 años tras el GP de Estados Unidos 2023."
  },
  {
    id: "lawson",
    name: "Liam Lawson",
    code: "LAW",
    number: 30,
    team: "RB / AlphaTauri",
    country: "Nueva Zelanda",
    countryCode: "NZ",
    championships: 0,
    podiums: 0,
    wins: 0,
    debutYear: 2023,
    lastYear: 2026,
    points: 6,
    poles: 0,
    gps: 11,
    helmetColor: "#0033cc",
    color: "#061389",
    stats: { speed: 89, consistency: 90, racecraft: 91, experience: 78 },
    quote: "Ready to take every single opportunity.",
    funFact: "Sustituto milagroso de Ricciardo en 2023 puntuando en Singapur en apenas su 3ª carrera."
  },
  {
    id: "doohan",
    name: "Jack Doohan",
    code: "DOO",
    number: 7,
    team: "Alpine (2025)",
    country: "Australia",
    countryCode: "AU",
    championships: 0,
    podiums: 0,
    wins: 0,
    debutYear: 2024,
    lastYear: 2026,
    points: 0,
    poles: 0,
    gps: 1,
    helmetColor: "#0078c1",
    color: "#0078c1",
    stats: { speed: 88, consistency: 87, racecraft: 88, experience: 72 },
    quote: "Racing runs in the family blood.",
    funFact: "Hijo del legendario pentacampeón de 500cc Mick Doohan, promocionado al asiento titular de Alpine en F1."
  },
  {
    id: "delarosa",
    name: "Pedro de la Rosa",
    code: "DLR",
    number: 17,
    team: "McLaren / Arrows / Jaguar / Sauber / HRT",
    country: "España",
    countryCode: "ES",
    championships: 0,
    podiums: 1,
    wins: 0,
    debutYear: 1999,
    lastYear: 2012,
    points: 35,
    poles: 0,
    gps: 107,
    helmetColor: "#ffcc00",
    color: "#ff8000",
    stats: { speed: 90, consistency: 94, racecraft: 91, experience: 96 },
    quote: "Un podio en Hungría sabe a gloria bendita.",
    funFact: "Ostenta el récord de vuelta rápida en carrera en Baréin desde 2005 y fue 2º con McLaren en Hungría 2006."
  },
  {
    id: "gene",
    name: "Marc Gené",
    code: "GEN",
    number: 21,
    team: "Minardi / Williams / Ferrari",
    country: "España",
    countryCode: "ES",
    championships: 0,
    podiums: 0,
    wins: 0,
    debutYear: 1999,
    lastYear: 2004,
    points: 5,
    poles: 0,
    gps: 36,
    helmetColor: "#ffff00",
    color: "#e80020",
    stats: { speed: 88, consistency: 92, racecraft: 89, experience: 95 },
    quote: "El punto de Nürburgring con Minardi fue pura magia.",
    funFact: "Sumó el mítico punto de Minardi en Nürburgring 1999 y fue 5º sustituyendo a Ralf Schumacher en Monza 2003."
  },
  {
    id: "maldonado",
    name: "Pastor Maldonado",
    code: "MAL",
    number: 18,
    team: "Williams / Lotus",
    country: "Venezuela",
    countryCode: "VE",
    championships: 0,
    podiums: 1,
    wins: 1,
    debutYear: 2011,
    lastYear: 2015,
    points: 76,
    poles: 1,
    gps: 96,
    helmetColor: "#990000",
    color: "#00a3e0",
    stats: { speed: 93, consistency: 75, racecraft: 89, experience: 88 },
    quote: "Ganar el Gran Premio de España saliendo desde la Pole fue un sueño irrepetible.",
    funFact: "Logró la última victoria de la historia de Williams Grand Prix saliendo desde la pole en Barcelona 2012."
  },
  {
    id: "kobayashi",
    name: "Kamui Kobayashi",
    code: "KOB",
    number: 14,
    team: "Sauber / Toyota / Caterham",
    country: "Japón",
    countryCode: "JP",
    championships: 0,
    podiums: 1,
    wins: 0,
    debutYear: 2009,
    lastYear: 2014,
    points: 125,
    poles: 0,
    gps: 76,
    helmetColor: "#ff0033",
    color: "#ffffff",
    stats: { speed: 92, consistency: 88, racecraft: 96, experience: 90 },
    quote: "¡KAMUI, KAMUI! en el podio de Suzuka.",
    funFact: "Histórico podio en casa en Suzuka 2012 ante el delirio de toda la afición japonesa."
  },
  {
    id: "grosjean",
    name: "Romain Grosjean",
    code: "GRO",
    number: 8,
    team: "Lotus / Haas / Renault",
    country: "Francia",
    countryCode: "FR",
    championships: 0,
    podiums: 10,
    wins: 0,
    debutYear: 2009,
    lastYear: 2020,
    points: 391,
    poles: 0,
    gps: 181,
    helmetColor: "#ff8000",
    color: "#004225",
    stats: { speed: 92, consistency: 84, racecraft: 90, experience: 92 },
    quote: "El hombre del fuego: sobreviví para contarlo.",
    funFact: "10 podios con Lotus y superviviente milagroso del terrible choque e incendio de Baréin 2020."
  },
  {
    id: "kvyat",
    name: "Daniil Kvyat",
    code: "KVY",
    number: 26,
    team: "Red Bull / Toro Rosso / AlphaTauri",
    country: "Rusia",
    countryCode: "RU",
    championships: 0,
    podiums: 3,
    wins: 0,
    debutYear: 2014,
    lastYear: 2020,
    points: 202,
    poles: 0,
    gps: 112,
    helmetColor: "#ffffff",
    color: "#061389",
    stats: { speed: 90, consistency: 87, racecraft: 91, experience: 89 },
    quote: "The Torpedo strikes back!",
    funFact: "Apodado 'El Torpedo' por Sebastian Vettel; logró podios con Red Bull y Toro Rosso (Hockenheim 2019)."
  },
  {
    id: "fisichella",
    name: "Giancarlo Fisichella",
    code: "FIS",
    number: 3,
    team: "Renault / Jordan / Force India / Ferrari / Benetton / Sauber",
    country: "Italia",
    countryCode: "IT",
    championships: 0,
    podiums: 19,
    wins: 3,
    debutYear: 1996,
    lastYear: 2009,
    points: 275,
    poles: 4,
    gps: 231,
    helmetColor: "#ffff00",
    color: "#0078c1",
    stats: { speed: 92, consistency: 93, racecraft: 92, experience: 97 },
    quote: "Pole y podio para Force India en Spa 2009.",
    funFact: "Pieza clave en los títulos de constructores de Renault en 2005 y 2006 como escudero de Fernando Alonso."
  },
  {
    id: "trulli",
    name: "Jarno Trulli",
    code: "TRU",
    number: 9,
    team: "Renault / Toyota / Jordan / Prost / Lotus",
    country: "Italia",
    countryCode: "IT",
    championships: 0,
    podiums: 11,
    wins: 1,
    debutYear: 1997,
    lastYear: 2011,
    points: 246,
    poles: 4,
    gps: 256,
    helmetColor: "#ffffff",
    color: "#0078c1",
    stats: { speed: 95, consistency: 90, racecraft: 91, experience: 96 },
    quote: "The Trulli Train is coming through!",
    funFact: "Maestro a una vuelta; ganó el GP de Mónaco 2004 desde la pole dominando de principio a fin."
  },
  {
    id: "ralf_schumacher",
    name: "Ralf Schumacher",
    code: "RSC",
    number: 5,
    team: "Williams / Jordan / Toyota",
    country: "Alemania",
    countryCode: "DE",
    championships: 0,
    podiums: 27,
    wins: 6,
    debutYear: 1997,
    lastYear: 2007,
    points: 329,
    poles: 6,
    gps: 182,
    helmetColor: "#ffff00",
    color: "#00a3e0",
    stats: { speed: 93, consistency: 89, racecraft: 91, experience: 95 },
    quote: "Vencer a Michael en Montreal 2001 fue el día más grande de mi vida.",
    funFact: "Primeros hermanos en la historia de la F1 en ganar carreras y compartir la primera fila de parrilla."
  },
  {
    id: "frentzen",
    name: "Heinz-Harald Frentzen",
    code: "HHF",
    number: 8,
    team: "Jordan / Williams / Sauber / Prost / Arrows",
    country: "Alemania",
    countryCode: "DE",
    championships: 0,
    podiums: 18,
    wins: 3,
    debutYear: 1994,
    lastYear: 2003,
    points: 174,
    poles: 2,
    gps: 160,
    helmetColor: "#003366",
    color: "#eab308",
    stats: { speed: 93, consistency: 92, racecraft: 92, experience: 95 },
    quote: "Peleamos por el título con Jordan en 1999 hasta las últimas carreras.",
    funFact: "Subcampeón del mundo en 1997 y protagonista de la histórica temporada 1999 con Jordan Grand Prix."
  },
  {
    id: "berger",
    name: "Gerhard Berger",
    code: "BER",
    number: 28,
    team: "Ferrari / McLaren / Benetton / ATS / Arrows",
    country: "Austria",
    countryCode: "AT",
    championships: 0,
    podiums: 48,
    wins: 10,
    debutYear: 1984,
    lastYear: 1997,
    points: 385,
    poles: 12,
    gps: 210,
    helmetColor: "#0033cc",
    color: "#e80020",
    stats: { speed: 93, consistency: 90, racecraft: 93, experience: 97 },
    quote: "Monza 1988: el doblete de Ferrari tras morir Don Enzo.",
    funFact: "Ganó en Monza 1988 para Ferrari semanas después de la muerte de Enzo Ferrari, quebrando la racha invicta de McLaren."
  },
  {
    id: "alesi",
    name: "Jean Alesi",
    code: "ALE",
    number: 27,
    team: "Ferrari / Benetton / Tyrrell / Sauber / Prost / Jordan",
    country: "Francia",
    countryCode: "FR",
    championships: 0,
    podiums: 32,
    wins: 1,
    debutYear: 1989,
    lastYear: 2001,
    points: 241,
    poles: 2,
    gps: 202,
    helmetColor: "#003399",
    color: "#e80020",
    stats: { speed: 94, consistency: 86, racecraft: 95, experience: 96 },
    quote: "El número 27 de Ferrari en el corazón de los tifosi.",
    funFact: "Ídolo de masas de los tifosi; ganó el GP de Canadá 1995 el mismo día de su 31 cumpleaños."
  },
  {
    id: "alboreto",
    name: "Michele Alboreto",
    code: "ALB",
    number: 27,
    team: "Ferrari / Tyrrell / Arrows / Footwork / Minardi",
    country: "Italia",
    countryCode: "IT",
    championships: 0,
    podiums: 23,
    wins: 5,
    debutYear: 1981,
    lastYear: 1994,
    points: 186,
    poles: 2,
    gps: 215,
    helmetColor: "#003366",
    color: "#e80020",
    stats: { speed: 92, consistency: 91, racecraft: 93, experience: 96 },
    quote: "El último italiano elegido directamente por Enzo Ferrari.",
    funFact: "Subcampeón del mundo en 1985 con Ferrari tras una gran pugna frente a Alain Prost."
  },
  {
    id: "arnoux",
    name: "René Arnoux",
    code: "ARN",
    number: 16,
    team: "Renault / Ferrari / Ligier / Martini",
    country: "Francia",
    countryCode: "FR",
    championships: 0,
    podiums: 22,
    wins: 7,
    debutYear: 1978,
    lastYear: 1989,
    points: 181,
    poles: 18,
    gps: 164,
    helmetColor: "#ffffff",
    color: "#ff8000",
    stats: { speed: 95, consistency: 87, racecraft: 96, experience: 94 },
    quote: "El duelo de Dijon con Gilles fue el automovilismo en estado puro.",
    funFact: "Protagonista junto a Gilles Villeneuve del duelo más electrizante de la historia en Dijon 1979."
  },
  {
    id: "cevert",
    name: "François Cevert",
    code: "CEV",
    number: 6,
    team: "Tyrrell / March",
    country: "Francia",
    countryCode: "FR",
    championships: 0,
    podiums: 13,
    wins: 1,
    debutYear: 1970,
    lastYear: 1973,
    points: 89,
    poles: 0,
    gps: 47,
    helmetColor: "#003399",
    color: "#003893",
    stats: { speed: 93, consistency: 91, racecraft: 93, experience: 88 },
    quote: "El príncipe azul de la F1 y heredero de Jackie Stewart.",
    funFact: "Ganó el GP de Estados Unidos 1971 en Watkins Glen y era el heredero natural de Stewart antes de su trágico accidente en 1973."
  },
  {
    id: "bruce_mclaren",
    name: "Bruce McLaren",
    code: "MCL",
    number: 2,
    team: "McLaren / Cooper",
    country: "Nueva Zelanda",
    countryCode: "NZ",
    championships: 0,
    podiums: 27,
    wins: 4,
    debutYear: 1958,
    lastYear: 1970,
    points: 196,
    poles: 3,
    gps: 104,
    helmetColor: "#ffffff",
    color: "#ff8000",
    stats: { speed: 93, consistency: 95, racecraft: 94, experience: 96 },
    quote: "La vida se mide en logros, no solo en años transcurridos.",
    funFact: "Fundador de la escudería McLaren; ganó en Spa 1968 logrando la primera victoria de su propio monoplaza."
  },
  {
    id: "ickx",
    name: "Jacky Ickx",
    code: "ICK",
    number: 7,
    team: "Ferrari / Brabham / Lotus / McLaren / Williams",
    country: "Bélgica",
    countryCode: "BE",
    championships: 0,
    podiums: 25,
    wins: 8,
    debutYear: 1966,
    lastYear: 1979,
    points: 181,
    poles: 13,
    gps: 120,
    helmetColor: "#001f3f",
    color: "#e80020",
    stats: { speed: 95, consistency: 95, racecraft: 97, experience: 97 },
    quote: "El Rey de la Lluvia y de las 24 Horas de Le Mans.",
    funFact: "Dos veces subcampeón del mundo (1969 y 1970) y maestro absoluto bajo lluvia en Nürburgring y Rouen."
  },
  {
    id: "reutemann",
    name: "Carlos Reutemann",
    code: "REU",
    number: 2,
    team: "Williams / Ferrari / Brabham / Lotus",
    country: "Argentina",
    countryCode: "AR",
    championships: 0,
    podiums: 45,
    wins: 12,
    debutYear: 1972,
    lastYear: 1982,
    points: 310,
    poles: 6,
    gps: 146,
    helmetColor: "#003399",
    color: "#00a3e0",
    stats: { speed: 94, consistency: 93, racecraft: 94, experience: 96 },
    quote: "Lole Reutemann: precisión pura al volante.",
    funFact: "Subcampeón del mundo en 1981 por un único punto en Las Vegas tras una temporada épica."
  },
  {
    id: "irvine",
    name: "Eddie Irvine",
    code: "IRV",
    number: 4,
    team: "Ferrari / Jaguar / Jordan",
    country: "Reino Unido",
    countryCode: "GB",
    championships: 0,
    podiums: 26,
    wins: 4,
    debutYear: 1993,
    lastYear: 2002,
    points: 191,
    poles: 0,
    gps: 148,
    helmetColor: "#ff7700",
    color: "#e80020",
    stats: { speed: 91, consistency: 92, racecraft: 92, experience: 94 },
    quote: "Subcampeón en 1999 luchando hasta Japón.",
    funFact: "Lideró a Ferrari en la lucha por el campeonato mundial de 1999 tras la fractura de pierna de Michael Schumacher."
  },
  {
    id: "jos_verstappen",
    name: "Jos Verstappen",
    code: "JVE",
    number: 6,
    team: "Benetton / Arrows / Minardi / Stewart / Tyrrell",
    country: "Países Bajos",
    countryCode: "NL",
    championships: 0,
    podiums: 2,
    wins: 0,
    debutYear: 1994,
    lastYear: 2003,
    points: 17,
    poles: 0,
    gps: 107,
    helmetColor: "#ff4d00",
    color: "#00a3e0",
    stats: { speed: 89, consistency: 84, racecraft: 90, experience: 94 },
    quote: "Jos the Boss: el fuego de Hockenheim '94.",
    funFact: "Padre de Max Verstappen; logró 2 podios en 1994 con Benetton y sobrevivió a la famosa bola de fuego en boxes."
  }
];

export const F1_CIRCUITS = [
  {
    id: "monaco",
    name: "Circuit de Monaco",
    city: "Monte Carlo",
    country: "Mónaco",
    countryCode: "MC",
    lengthKm: 3.337,
    turns: 19,
    firstGP: 1950,
    lapRecord: "1:12.909 (Lewis Hamilton, 2021)",
    drsZones: 1,
    trackType: "Callejero extremo",
    description: "El trazado más icónico, glamuroso y estrecho del planeta. Adelantar es casi imposible.",
    clues: [
      "Microclima mediterráneo. Asfalto urbano ultra resbaladizo con cambios drásticos de luz al mediodía.",
      "Caja de cambios sometida a más de 3.600 cambios por gran premio en menos de 260 km de distancia total.",
      "Se requiere el ángulo de giro de dirección más extremo de todo el campeonato para no rozar las barreras."
    ],
    streetView: {
      lat: 43.7347,
      lng: 7.4206,
      heading: 140,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=43.7347,7.4206&layer=c&cbll=43.7347,7.4206&cbp=11,140,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 100 240 L 140 240 L 170 210 L 220 210 C 250 200 280 230 300 210 L 320 180 C 330 150 310 130 280 130 L 220 130 C 200 120 180 90 200 70 L 250 60 C 270 50 250 20 210 30 L 140 50 C 110 60 90 90 100 130 L 110 170 C 110 200 80 210 70 230 Z"
  },
  {
    id: "spa",
    name: "Circuit de Spa-Francorchamps",
    city: "Stavelot",
    country: "Bélgica",
    countryCode: "BE",
    lengthKm: 7.004,
    turns: 19,
    firstGP: 1950,
    lapRecord: "1:46.286 (Valtteri Bottas, 2018)",
    drsZones: 2,
    trackType: "Histórico ondulado",
    description: "La montaña rusa de las Ardenas. El circuito más largo y exigente con el clima más impredecible.",
    clues: [
      "Compresión vertical superior a 3.5G que hunde las suspensiones contra el suelo a más de 300 km/h.",
      "Fenómeno meteorológico local: llueve en el sector 3 mientras el sector 1 permanece completamente seco.",
      "Tiempo de vuelta superior a los 104 segundos en condiciones óptimas de clasificación."
    ],
    streetView: {
      lat: 50.438014,
      lng: 5.968094,
      heading: 45,
      pitch: 0,
      panoId: "CAoSFkNJSE0wb2dLRUlDQWdJQ0VvcE91WGc.",
      embedUrl: "https://maps.google.com/maps?q=50.438014,5.968094&layer=c&cbll=50.438014,5.968094&panoid=CAoSFkNJSE0wb2dLRUlDQWdJQ0VvcE91WGc.&cbp=11,45,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 60 180 L 110 190 L 160 170 L 170 120 L 220 80 L 310 60 L 340 90 L 320 130 L 300 150 L 310 190 L 260 210 L 220 180 L 180 230 L 130 240 L 80 220 Z"
  },
  {
    id: "silverstone",
    name: "Silverstone Circuit",
    city: "Northamptonshire",
    country: "Reino Unido",
    countryCode: "GB",
    lengthKm: 5.891,
    turns: 18,
    firstGP: 1950,
    lapRecord: "1:27.097 (Max Verstappen, 2020)",
    drsZones: 2,
    trackType: "Templo de alta velocidad",
    description: "Cuna histórica del campeonato mundial de F1 en 1950, célebre por Maggotts, Becketts y Chapel.",
    clues: [
      "Vientos cruzados racheados permanentes debido a pistas de aterrizaje abiertas en un altiplano.",
      "Los neumáticos delanteros derechos sufren la mayor carga de energía lateral de todo el calendario.",
      "Curva de entrada rápida tomada en 7ª velocidad a más de 285 km/h sin apenas rozar el pedal de freno."
    ],
    streetView: {
      lat: 52.0786,
      lng: -1.0169,
      heading: 260,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=52.0786,-1.0169&layer=c&cbll=52.0786,-1.0169&cbp=11,260,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 70 200 L 130 230 L 190 220 L 240 240 L 290 200 L 330 150 L 300 100 L 250 80 L 180 70 L 120 90 L 90 140 Z"
  },
  {
    id: "monza",
    name: "Autodromo Nazionale Monza",
    city: "Monza",
    country: "Italia",
    countryCode: "IT",
    lengthKm: 5.793,
    turns: 11,
    firstGP: 1950,
    lapRecord: "1:21.046 (Rubens Barrichello, 2004)",
    drsZones: 2,
    trackType: "Templo de la Velocidad",
    description: "Poco apoyo aerodinámico, velocidades punta superiores a 350 km/h y los tifosi de Ferrari.",
    clues: [
      "Configuración aerodinámica 'cuchara' de mínima resistencia al avance (menos de 15 grados de alerón).",
      "Los monoplazas pasan más del 78% de la vuelta con el acelerador 100% abierto a fondo.",
      "Frenada desde 355 km/h hasta 75 km/h en apenas 120 metros soportando picos de 5.8G negativos."
    ],
    streetView: {
      lat: 45.6206,
      lng: 9.2811,
      heading: 30,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=45.6206,9.2811&layer=c&cbll=45.6206,9.2811&cbp=11,30,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 50 160 L 180 60 L 290 50 L 320 80 L 300 120 L 280 140 L 310 180 L 280 230 L 120 240 L 60 210 Z"
  },
  {
    id: "suzuka",
    name: "Suzuka International Racing Course",
    city: "Suzuka, Mie",
    country: "Japón",
    countryCode: "JP",
    lengthKm: 5.807,
    turns: 18,
    firstGP: 1987,
    lapRecord: "1:30.983 (Lewis Hamilton, 2019)",
    drsZones: 1,
    trackType: "Figura en 8",
    description: "Único trazado en forma de ocho que cruza por un puente. Las 'Eses' iniciales y la 130R fascinan a pilotos.",
    clues: [
      "Ritmo rítmico implacable: un error de colocación de 10 cm en el vértice 1 arruina los siguientes 4 giros.",
      "La carga aerodinámica se iguala en ambos costados gracias a su particular cruce en puente a desnivel.",
      "Curva a izquierdas ciega negociada en 8ª marcha a fondo absoluto con los bordillos al límite."
    ],
    streetView: {
      lat: 34.8431,
      lng: 136.5410,
      heading: 180,
      pitch: 5,
      embedUrl: "https://maps.google.com/maps?q=34.8431,136.5410&layer=c&cbll=34.8431,136.5410&cbp=11,180,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 70 80 C 110 50 170 70 190 100 C 220 140 210 180 240 200 C 270 220 320 200 330 160 C 340 120 290 110 260 130 C 220 160 190 220 150 240 C 110 250 80 210 90 160 Z"
  },
  {
    id: "interlagos",
    name: "Autódromo José Carlos Pace (Interlagos)",
    city: "São Paulo",
    country: "Brasil",
    countryCode: "BR",
    lengthKm: 4.309,
    turns: 15,
    firstGP: 1973,
    lapRecord: "1:10.540 (Valtteri Bottas, 2018)",
    drsZones: 2,
    trackType: "Sentido antihorario",
    description: "Tierra de Ayrton Senna, carreras con lluvia torrencial, adelantamientos y finales de campeonato de infarto.",
    clues: [
      "Circuito a más de 750 metros de altitud donde el aire fino reduce la densidad aerodinámica un 8%.",
      "El cuello del piloto sufre fatiga asimétrica severa debido al sentido de giro anti-horario.",
      "Subida empinada en curva ciega donde la tracción en mojado suele provocar aquaplaning masivo."
    ],
    streetView: {
      lat: -23.7036,
      lng: -46.6997,
      heading: 320,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=-23.7036,-46.6997&layer=c&cbll=-23.7036,-46.6997&cbp=11,320,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 100 80 L 160 60 L 220 80 L 260 120 L 230 170 L 200 150 L 170 180 L 210 230 L 150 240 L 90 200 L 70 130 Z"
  },
  {
    id: "madrid",
    name: "MadCool Circuito IFEMA Madrid (2026)",
    city: "Madrid",
    country: "España",
    countryCode: "ES",
    lengthKm: 5.474,
    turns: 20,
    firstGP: 2026,
    lapRecord: "Por debutar en 2026",
    drsZones: 3,
    trackType: "Híbrido Urbano / Permanente",
    description: "El nuevo circuito español con peralte masivo estilo curva Monumental en Valdebebas / IFEMA.",
    clues: [
      "Trazado híbrido con un sector permanente peraltado a más de 12 grados de inclinación lateral.",
      "Altitud cercana a los 650 metros sobre el nivel del mar con temperaturas de asfalto estivales sobre 50°C.",
      "Transición entre túneles de enlace y asfalto de autovía adaptado a especificación FIA Grado 1."
    ],
    streetView: {
      lat: 40.4637,
      lng: -3.6169,
      heading: 100,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=40.4637,-3.6169&layer=c&cbll=40.4637,-3.6169&cbp=11,100,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 80 100 L 180 80 L 250 100 L 310 140 L 290 200 L 220 220 L 170 190 L 130 220 L 80 180 Z"
  },
  {
    id: "sepang",
    name: "Sepang International Circuit",
    city: "Kuala Lumpur",
    country: "Malasia",
    countryCode: "MY",
    lengthKm: 5.543,
    turns: 15,
    firstGP: 1999,
    lapRecord: "1:34.080 (Sebastian Vettel, 2017)",
    drsZones: 2,
    trackType: "Histórico Moderno (1999-2017)",
    description: "La obra maestra pionera de Hermann Tilke con calor asfixiante, humedad extrema y dos larguísimas rectas unidas por una horquilla.",
    clues: [
      "Humedad superior al 85% que provoca que los pilotos pierdan hasta 3 kg de masa corporal por deshidratación.",
      "Dos rectas monumentales de casi 1 km conectadas por una horquilla ultra cerrada frente a una tribuna con forma de hoja de palmera.",
      "Lluvias monzónicas vespertinas que obligaban habitualmente a suspender carreras por inundación repentina."
    ],
    streetView: {
      lat: 2.7606,
      lng: 101.7374,
      heading: 310,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=2.7606,101.7374&layer=c&cbll=2.7606,101.7374&cbp=11,310,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 80 200 L 140 230 L 200 180 L 250 210 L 300 140 L 260 90 L 180 110 L 110 130 Z"
  },
  {
    id: "istanbul",
    name: "Intercity Istanbul Park",
    city: "Estambul",
    country: "Turquía",
    countryCode: "TR",
    lengthKm: 5.338,
    turns: 14,
    firstGP: 2005,
    lapRecord: "1:24.770 (Juan Pablo Montoya, 2005)",
    drsZones: 2,
    trackType: "Histórico Moderno (2005-2011, 2020-2021)",
    description: "Famoso por su legendaria 'Curva 8', un cuádruple vértice a izquierdas tomado a fondo que destrozaba el cuello y los neumáticos.",
    clues: [
      "Alberga la curva multi-vértice más destructiva de la era moderna: más de 5G laterales sostenidos durante casi 7 segundos.",
      "Sentido de giro anti-horario con desniveles pronunciados apodado por los ingenieros 'el Spa de Oriente'.",
      "Asfalto reasfaltado en 2020 que convirtió la pista en una pista de patinaje sobre hielo bajo la lluvia."
    ],
    streetView: {
      lat: 40.9517,
      lng: 29.4050,
      heading: 120,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=40.9517,29.4050&layer=c&cbll=40.9517,29.4050&cbp=11,120,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 90 120 L 180 70 L 280 80 L 330 150 L 300 220 L 220 200 L 150 240 L 80 180 Z"
  },
  {
    id: "indianapolis",
    name: "Indianapolis Motor Speedway (Road Course)",
    city: "Indianápolis, Indiana",
    country: "Estados Unidos",
    countryCode: "US",
    lengthKm: 4.192,
    turns: 13,
    firstGP: 2000,
    lapRecord: "1:10.399 (Rubens Barrichello, 2004)",
    drsZones: 1,
    trackType: "Histórico (2000-2007)",
    description: "El mítico 'Brickyard' adaptado a la F1, famoso por la curva peraltada final tomada en sentido inverso y el fiasco de neumáticos de 2005 con 6 monoplazas.",
    clues: [
      "El último sector usaba la curva peraltada a 9 grados del legendario óvalo de las 500 Millas.",
      "Fue el escenario de la polémica carrera de 2005 donde solo tomaron la salida 6 coches por fallos de delaminación de neumáticos.",
      "La línea de meta cruza directamente sobre la histórica franja original de ladrillos 'The Yard of Bricks'."
    ],
    streetView: {
      lat: 39.7950,
      lng: -86.2348,
      heading: 0,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=39.7950,-86.2348&layer=c&cbll=39.7950,-86.2348&cbp=11,0,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 70 80 L 250 80 L 320 180 L 300 240 L 180 240 L 100 200 L 70 140 Z"
  },
  {
    id: "marinabay",
    name: "Marina Bay Street Circuit",
    city: "Singapur",
    country: "Singapur",
    countryCode: "SG",
    lengthKm: 4.940,
    turns: 19,
    firstGP: 2008,
    lapRecord: "1:34.486 (Daniel Ricciardo, 2024)",
    drsZones: 4,
    trackType: "Urbano Nocturno Actual",
    description: "La primera carrera nocturna en la historia de la F1. Calor tropical asfixiante bajo miles de focos de alta potencia.",
    clues: [
      "Primera carrera 100% nocturna de la historia del campeonato iluminada con más de 1.600 proyectores de luz artificial.",
      "Prácticamente siempre aparece el Safety Car debido a los muros de hormigón sin escapatorias.",
      "Los monoplazas cruzan el puente Anderson Bridge y pasan por debajo de la grada de la bahía flotante."
    ],
    streetView: {
      lat: 1.2913,
      lng: 103.8640,
      heading: 60,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=1.2913,103.8640&layer=c&cbll=1.2913,103.8640&cbp=11,60,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 100 220 L 140 220 L 180 190 L 240 190 L 290 150 L 310 110 L 250 80 L 180 90 L 110 140 Z"
  },
  {
    id: "valencia",
    name: "Valencia Street Circuit",
    city: "Valencia",
    country: "España",
    countryCode: "ES",
    lengthKm: 5.419,
    turns: 25,
    firstGP: 2008,
    lapRecord: "1:38.683 (Timo Glock, 2009)",
    drsZones: 2,
    trackType: "Histórico Urbano Portuario (2008-2012)",
    description: "Trazado urbano alrededor de la dársena de la America's Cup y el puente basculante. Inmortalizado por la épica remontada de Fernando Alonso en 2012.",
    clues: [
      "Circuito urbano diseñado alrededor de un puerto deportivo con un puente basculante móvil que cruzaban los coches en plena vuelta.",
      "Escenario de una de las victorias más emotivas de Ferrari saliendo desde la 11ª posición de parrilla en 2012.",
      "25 curvas cerradas de ángulo recto entre almacenes portuarios con temperaturas de asfalto mediterráneas sobre 45°C."
    ],
    streetView: {
      lat: 39.4616,
      lng: -0.3297,
      heading: 90,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=39.4616,-0.3297&layer=c&cbll=39.4616,-0.3297&cbp=11,90,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 90 200 L 170 210 L 240 180 L 320 180 L 300 120 L 220 110 L 150 130 L 80 160 Z"
  },
  {
    id: "nurburgring",
    name: "Nürburgring GP-Strecke",
    city: "Nürburg, Eifel",
    country: "Alemania",
    countryCode: "DE",
    lengthKm: 5.148,
    turns: 15,
    firstGP: 1951,
    lapRecord: "1:28.139 (Max Verstappen, 2020)",
    drsZones: 2,
    trackType: "Histórico Moderno (GP de Europa / Eifel)",
    description: "El mítico trazado de las montañas de Eifel, célebre por la chicane Veedol, la horquilla Castrol-S y un clima de niebla impredecible.",
    clues: [
      "Clima de montaña extremadamente frío donde los monoplazas han llegado a rodar con temperaturas ambientales de apenas 8°C.",
      "Ubicado junto al histórico 'Infierno Verde' (Nordschleife) de más de 20 km de longitud.",
      "La frenada en bajada hacia la primera curva a derechas suele provocar bloqueos masivos del tren delantero en la salida."
    ],
    streetView: {
      lat: 50.3341,
      lng: 6.9427,
      heading: 200,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=50.3341,6.9427&layer=c&cbll=50.3341,6.9427&cbp=11,200,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 100 180 L 180 190 L 240 160 L 300 140 L 270 80 L 200 90 L 130 110 L 80 140 Z"
  },
  {
    id: "yasmarina",
    name: "Yas Marina Circuit",
    city: "Abu Dhabi",
    country: "Emiratos Árabes Unidos",
    countryCode: "AE",
    lengthKm: 5.281,
    turns: 16,
    firstGP: 2009,
    lapRecord: "1:26.103 (Max Verstappen, 2021)",
    drsZones: 2,
    trackType: "Carrera Crepuscular Actual",
    description: "El cierre del campeonato mundial. Carrera que comienza con luz diurna y acaba de noche bajo focos junto al hotel W y el puerto.",
    clues: [
      "Carrera crepuscular: la temperatura del asfalto cae en picado hasta 12°C a medida que cae el sol en el desierto.",
      "La salida del pit lane cruza por un estrecho túnel subterráneo por debajo de la curva 1.",
      "Sede del desenlace más cardíaco y controvertido de la historia moderna del campeonato en la última vuelta de 2021."
    ],
    streetView: {
      lat: 24.4672,
      lng: 54.6031,
      heading: 340,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=24.4672,54.6031&layer=c&cbll=24.4672,54.6031&cbp=11,340,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 90 220 L 160 210 L 230 180 L 310 180 L 280 110 L 200 100 L 130 130 L 70 160 Z"
  },
  {
    id: "jeddah",
    name: "Jeddah Corniche Circuit",
    city: "Yeda",
    country: "Arabia Saudí",
    countryCode: "SA",
    lengthKm: 6.174,
    turns: 27,
    firstGP: 2021,
    lapRecord: "1:30.734 (Lewis Hamilton, 2021)",
    drsZones: 3,
    trackType: "Callejero de Ultra Velocidad Actual",
    description: "El trazado urbano más rápido y con mayor número de curvas del planeta. Promedios superiores a 250 km/h pegados al Mar Rojo.",
    clues: [
      "El circuito urbano más rápido del mundo: velocidades medias superiores a 252 km/h entre muros ciegos de hormigón.",
      "Es el trazado con más curvas de todo el calendario mundial: 27 curvas enlazadas a orillas del Mar Rojo.",
      "Curva 13 con peralte positivo de 12 grados tomada a gran aceleración lateral."
    ],
    streetView: {
      lat: 21.630738,
      lng: 39.104456,
      heading: 10,
      pitch: 0,
      panoId: "CAoSFkNJSE0wb2dLRUlDQWdJRHF5N2FmU3c.",
      embedUrl: "https://maps.google.com/maps?q=21.630738,39.104456&layer=c&cbll=21.630738,39.104456&panoid=CAoSFkNJSE0wb2dLRUlDQWdJRHF5N2FmU3c.&cbp=11,10,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 100 250 L 130 200 L 160 140 L 190 80 L 220 80 L 200 160 L 170 220 L 130 260 Z"
  },
  {
    id: "baku",
    name: "Baku City Circuit",
    city: "Bakú",
    country: "Azerbaiyán",
    countryCode: "AZ",
    lengthKm: 6.003,
    turns: 20,
    firstGP: 2016,
    lapRecord: "1:43.009 (Charles Leclerc, 2019)",
    drsZones: 2,
    trackType: "Callejero Mixto Actual",
    description: "Contraste radical entre la recta más larga de la F1 (2.2 km a más de 360 km/h) y el paso de apenas 7.6 metros junto al castillo medieval.",
    clues: [
      "La recta principal más larga de la Fórmula 1 moderna: más de 2.2 kilómetros a fondo alcanzando hasta 364 km/h con rebufo.",
      "La sección del castillo medieval (curvas 8 a 11) tiene un ancho de pista de tan solo 7.6 metros.",
      "Vientos fuertes racheados provenientes del Mar Caspio que desestabilizan los alerones en la frenada de la curva 1."
    ],
    streetView: {
      lat: 40.3725,
      lng: 49.8533,
      heading: 160,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=40.3725,49.8533&layer=c&cbll=40.3725,49.8533&cbp=11,160,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 60 210 L 180 210 L 270 210 L 330 180 L 270 120 L 200 110 L 120 140 L 70 180 Z"
  },
  {
    id: "cota",
    name: "Circuit of the Americas (COTA)",
    city: "Austin, Texas",
    country: "Estados Unidos",
    countryCode: "US",
    lengthKm: 5.513,
    turns: 20,
    firstGP: 2012,
    lapRecord: "1:36.169 (Charles Leclerc, 2019)",
    drsZones: 2,
    trackType: "Permanente Ondulado Actual",
    description: "Inspirado en las mejores curvas del mundo con la famosa subida ciega a la curva 1 con 41 metros de desnivel.",
    clues: [
      "Subida brutal hacia la curva 1 con una pendiente empinadísima de más de 41 metros de desnivel vertical.",
      "Primer sector compuesto por réplicas de las eses de Silverstone y Suzuka con asfalto con baches característicos de Texas.",
      "Complejo de curvas finales inspirado en la famosa Curva 8 de Estambul con cuádruple vértice a derechas."
    ],
    streetView: {
      lat: 30.1328,
      lng: -97.6411,
      heading: 240,
      pitch: 5,
      embedUrl: "https://maps.google.com/maps?q=30.1328,-97.6411&layer=c&cbll=30.1328,-97.6411&cbp=11,240,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 70 120 L 150 70 L 240 80 L 320 120 L 290 200 L 220 220 L 150 190 L 80 180 Z"
  },
  {
    id: "bahrain",
    name: "Bahrain International Circuit (Sakhir)",
    city: "Sakhir",
    country: "Baréin",
    countryCode: "BH",
    lengthKm: 5.412,
    turns: 15,
    firstGP: 2004,
    lapRecord: "1:31.447 (Pedro de la Rosa, 2005)",
    drsZones: 3,
    trackType: "Actual / Nocturno en Desierto (2004-presente)",
    description: "Pionero de Oriente Medio en F1 desde 2004. Arena del desierto soplada sobre el asfalto y frenadas abrasivas nocturnas.",
    clues: [
      "Viento constante del desierto que deposita arena fina abrasiva fuera de la trazada ideal durante todo el fin de semana.",
      "La frenada en apoyo cuesta abajo de la curva 10 genera bloqueos masivos de la rueda delantera izquierda.",
      "Récord de vuelta en carrera imbatido desde la temporada 2005 por un piloto probador español con motor V10."
    ],
    streetView: {
      lat: 26.0325,
      lng: 50.5106,
      heading: 330,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=26.0325,50.5106&layer=c&cbll=26.0325,50.5106&cbp=11,330,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 70 190 L 140 210 L 200 170 L 270 190 L 300 120 L 230 80 L 160 100 L 80 140 Z"
  },
  {
    id: "shanghai",
    name: "Shanghai International Circuit",
    city: "Shanghái",
    country: "China",
    countryCode: "CN",
    lengthKm: 5.451,
    turns: 16,
    firstGP: 2004,
    lapRecord: "1:32.238 (Michael Schumacher, 2004)",
    drsZones: 2,
    trackType: "Actual / Arquitectura Tilke (2004-presente)",
    description: "Diseñado con la forma del ideograma chino 'Shang' (上). Famoso por su interminable curva de caracol y la kilométrica recta trasera.",
    clues: [
      "Trazado inspirado en un carácter de caligrafía oriental ('Shang') construido sobre ciénagas pantanosas con pilotes subterráneos.",
      "La curva 1 y 2 forman un caracol concéntrico de 270 grados en desaceleración continua que castiga la goma delantera izquierda.",
      "Recta trasera de 1.170 metros que desemboca en una horquilla cerrada tomada a menos de 70 km/h."
    ],
    streetView: {
      lat: 31.339499,
      lng: 121.221638,
      heading: 270,
      pitch: 0,
      panoId: "CAoSHENJQUJJaENYcXNieWNKMjZXZk1HdWhYSFc0TmI.",
      embedUrl: "https://maps.google.com/maps?q=31.339499,121.221638&layer=c&cbll=31.339499,121.221638&panoid=CAoSHENJQUJJaENYcXNieWNKMjZXZk1HdWhYSFc0TmI.&cbp=11,270,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 80 180 L 150 220 L 220 180 L 290 200 L 320 130 L 270 70 L 190 90 L 120 120 Z"
  },
  {
    id: "melbourne",
    name: "Albert Park Circuit",
    city: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    lengthKm: 5.278,
    turns: 14,
    firstGP: 1996,
    lapRecord: "1:19.813 (Charles Leclerc, 2024)",
    drsZones: 4,
    trackType: "Semipermanente Urbano Actual (1996-presente)",
    description: "Trazado semipermanente alrededor de un lago artificial en un parque público. Tradicional apertura de temporada.",
    clues: [
      "Circuito semipermanente rodeando un lago artificial que el resto del año funciona como vía pública con límite de 50 km/h.",
      "Evolución de pista altísima del viernes al domingo por la acumulación gradual de goma sobre asfalto sucio de hojas y polvo.",
      "La chicane rápida de alta velocidad (curvas 9-10) se negocia a más de 250 km/h rozando las vallas de césped exterior."
    ],
    streetView: {
      lat: -37.8497,
      lng: 144.9680,
      heading: 150,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=-37.8497,144.9680&layer=c&cbll=-37.8497,144.9680&cbp=11,150,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 90 220 L 160 230 L 230 200 L 290 170 L 270 100 L 210 90 L 140 120 L 80 160 Z"
  },
  {
    id: "montreal",
    name: "Circuit Gilles Villeneuve",
    city: "Montreal, Quebec",
    country: "Canadá",
    countryCode: "CA",
    lengthKm: 4.361,
    turns: 14,
    firstGP: 1978,
    lapRecord: "1:13.078 (Valtteri Bottas, 2019)",
    drsZones: 2,
    trackType: "Semipermanente Isla Artificial Actual",
    description: "Ubicado en la isla de Notre-Dame del río San Lorenzo. Famoso por el temido 'Muro de los Campeones' al final de la chicane.",
    clues: [
      "Construido en una isla artificial creada con tierra excavada durante las obras del metro para la Expo de 1967.",
      "La salida de la chicane final está resguardada por un muro de hormigón donde han colisionado múltiples campeones del mundo.",
      "Circuito de 'Stop & Go' extremo que somete los discos de freno de carbono a más de 1.100°C en cada vuelta."
    ],
    streetView: {
      lat: 45.5003,
      lng: -73.5228,
      heading: 200,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=45.5003,-73.5228&layer=c&cbll=45.5003,-73.5228&cbp=11,200,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 70 170 L 160 170 L 260 160 L 320 140 L 280 100 L 190 90 L 110 110 L 60 130 Z"
  },
  {
    id: "hockenheim",
    name: "Hockenheimring Baden-Württemberg",
    city: "Hockenheim",
    country: "Alemania",
    countryCode: "DE",
    lengthKm: 4.574,
    turns: 17,
    firstGP: 1970,
    lapRecord: "1:13.780 (Kimi Räikkönen, 2004)",
    drsZones: 2,
    trackType: "Histórico Moderno (Rediseño 2002-2019)",
    description: "El mítico templo alemán rediseñado en 2002 para concentrar el público en el colosal estadio del Motodrom.",
    clues: [
      "Trazado recortado drásticamente en 2002 eliminando los sectores de bosque donde se superaban los 360 km/h.",
      "El último sector desemboca en un coliseo cerrado de tribunas escalonadas conocido por los pilotos como el Motodrom.",
      "Parabolika suave a fondo que desemboca en la horquilla de Spitzkehre, punto de adelantamiento por excelencia."
    ],
    streetView: {
      lat: 49.3278,
      lng: 8.5658,
      heading: 45,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=49.3278,8.5658&layer=c&cbll=49.3278,8.5658&cbp=11,45,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 90 190 L 170 210 L 250 180 L 310 130 L 270 80 L 180 80 L 120 120 L 70 150 Z"
  },
  {
    id: "magnycours",
    name: "Circuit de Nevers Magny-Cours",
    city: "Magny-Cours, Nièvre",
    country: "Francia",
    countryCode: "FR",
    lengthKm: 4.411,
    turns: 17,
    firstGP: 1991,
    lapRecord: "1:15.377 (Michael Schumacher, 2004)",
    drsZones: 1,
    trackType: "Histórico (1991-2008)",
    description: "Sede del GP de Francia en los años 90 y 2000 en el corazón rural de Francia, famoso por la rápida chicane de Adélaïde y la estrategia de 4 paradas de Schumacher en 2004.",
    clues: [
      "Circuito ubicado en el corazón rural de la campiña gala rodeado de praderas y ganaderías lejos de grandes capitales.",
      "Curvas bautizadas en homenaje a otros trazados míticos (Adélaïde, Estoril, Imola, Nürburgring).",
      "Escenario de una victoria histórica de Michael Schumacher en 2004 completando una estrategia inverosímil de 4 paradas en boxes."
    ],
    streetView: {
      lat: 46.864759,
      lng: 3.163427,
      heading: 180,
      pitch: 0,
      panoId: "p7gCUJlw-lv83DVNDB0ZBg",
      embedUrl: "https://maps.google.com/maps?q=46.864759,3.163427&layer=c&cbll=46.864759,3.163427&panoid=p7gCUJlw-lv83DVNDB0ZBg&cbp=11,180,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 80 180 L 160 190 L 240 160 L 300 120 L 260 80 L 170 70 L 110 110 L 60 140 Z"
  },
  {
    id: "fuji",
    name: "Fuji Speedway",
    city: "Oyama, Shizuoka",
    country: "Japón",
    countryCode: "JP",
    lengthKm: 4.563,
    turns: 16,
    firstGP: 1976,
    lapRecord: "1:18.426 (Felipe Massa, 2008)",
    drsZones: 1,
    trackType: "Histórico Moderno Tilke (2007-2008)",
    description: "A los pies del monte Fuji. Célebre por su recta de salida y meta de casi 1.5 km y el diluvio nipón de 2007.",
    clues: [
      "Situado en las faldas de un volcán sagrado nevado, donde la niebla y la lluvia torrencial colapsaron la carrera de 2007.",
      "Posee una de las rectas de meta más interminables del automovilismo: casi 1.500 metros en aceleración plana.",
      "El último sector fue reconfigurado con una serie de curvas cerradas y ciegas de tercera marcha en subida continua."
    ],
    streetView: {
      lat: 35.3719,
      lng: 138.9269,
      heading: 210,
      pitch: 5,
      embedUrl: "https://maps.google.com/maps?q=35.3719,138.9269&layer=c&cbll=35.3719,138.9269&cbp=11,210,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 70 160 L 220 160 L 290 140 L 310 90 L 240 70 L 170 90 L 120 110 L 60 130 Z"
  },
  {
    id: "zandvoort",
    name: "Circuit Zandvoort",
    city: "Zandvoort",
    country: "Países Bajos",
    countryCode: "NL",
    lengthKm: 4.259,
    turns: 14,
    firstGP: 1952,
    lapRecord: "1:11.097 (Lewis Hamilton, 2021)",
    drsZones: 2,
    trackType: "Actual / Peraltado Costero (Retorno 2021-presente)",
    description: "Incrustado entre dunas de arena en la costa del Mar del Norte. Cuenta con curvas peraltadas a 18 y 19 grados al estilo Indianápolis.",
    clues: [
      "Ubicado entre dunas de arena en la costa del Mar del Norte donde la brisa marina arroja arena a la pista.",
      "Dos de sus curvas (Hugenholtz y Arie Luyendyk) cuentan con peraltes extremos de hasta 18 y 19 grados (el doble que Indianápolis).",
      "Pista de vieja escuela extremadamente angosta con trampas de grava esperando a escasos centímetros de la línea blanca."
    ],
    streetView: {
      lat: 52.3888,
      lng: 4.5409,
      heading: 260,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=52.3888,4.5409&layer=c&cbll=52.3888,4.5409&cbp=11,260,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 80 180 L 160 200 L 240 180 L 290 140 L 270 90 L 190 70 L 120 90 L 60 130 Z"
  },
  {
    id: "redbullring",
    name: "Red Bull Ring (Spielberg)",
    city: "Spielberg, Estiria",
    country: "Austria",
    countryCode: "AT",
    lengthKm: 4.318,
    turns: 10,
    firstGP: 1970,
    lapRecord: "1:05.619 (Carlos Sainz, 2020)",
    drsZones: 3,
    trackType: "Actual / Montaña Estiria (Retorno 2014-presente)",
    description: "El tiempo de vuelta más corto de la temporada (poco más de un minuto). Fuertes desniveles en los Alpes austríacos y 3 zonas de DRS seguidas.",
    clues: [
      "Circuito con el tiempo de vuelta más veloz de todo el campeonato (alrededor de 63-65 segundos por giro en clasificación).",
      "Tiene apenas 10 curvas oficiales y tres zonas consecutivas de DRS que favorecen adelantamientos constantes.",
      "Gran estatua de un toro de acero de 18 metros de altura situada en el centro del trazado alpino."
    ],
    streetView: {
      lat: 47.2197,
      lng: 14.7647,
      heading: 100,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=47.2197,14.7647&layer=c&cbll=47.2197,14.7647&cbp=11,100,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 90 200 L 190 210 L 280 160 L 260 90 L 170 80 L 100 130 Z"
  },
  {
    id: "hungaroring",
    name: "Hungaroring",
    city: "Mogyoród, Budapest",
    country: "Hungría",
    countryCode: "HU",
    lengthKm: 4.381,
    turns: 14,
    firstGP: 1986,
    lapRecord: "1:16.627 (Lewis Hamilton, 2020)",
    drsZones: 2,
    trackType: "Actual / Mónaco sin Muros (1986-presente)",
    description: "Apodado 'Mónaco sin muros' o 'pista de karting gigante'. Calor sofocante de verano en Europa Central y adelantamientos muy disputados.",
    clues: [
      "Conocido en el paddock como 'un karting gigante de F1' o 'Mónaco sin muros' debido a la sucesión incesante de curvas lentas.",
      "Temperaturas habituales de asfalto en julio/agosto que superan con frecuencia los 55°C.",
      "Histórico lugar donde Fernando Alonso logró su primera victoria en la F1 en la temporada 2003 con Renault."
    ],
    streetView: {
      lat: 47.582806,
      lng: 19.250245,
      heading: 320,
      pitch: 0,
      panoId: "CAoSFkNJSE0wb2dLRUlDQWdJRGFwSmVmWnc.",
      embedUrl: "https://maps.google.com/maps?q=47.582806,19.250245&layer=c&cbll=47.582806,19.250245&panoid=CAoSFkNJSE0wb2dLRUlDQWdJRGFwSmVmWnc.&cbp=11,320,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 80 170 L 150 190 L 230 180 L 290 140 L 260 80 L 180 80 L 120 110 L 60 140 Z"
  },
  {
    id: "lasvegas",
    name: "Las Vegas Strip Circuit",
    city: "Las Vegas, Nevada",
    country: "Estados Unidos",
    countryCode: "US",
    lengthKm: 6.201,
    turns: 17,
    firstGP: 2023,
    lapRecord: "1:35.490 (Oscar Piastri, 2023)",
    drsZones: 2,
    trackType: "Actual / Urbano Nocturno Neón (2023-presente)",
    description: "Los monoplazas vuelan a 350 km/h por el mítico 'Strip' frente al Bellagio, Caesar's Palace y la gigantesca MSG Sphere.",
    clues: [
      "Las temperaturas nocturnas en noviembre caen cerca de los 10°C, haciendo que calentar los neumáticos sea un reto crítico de adherencia.",
      "Recta interminable de casi 2 km por una de las avenidas con mayor concentración de casinos y hoteles iluminados del planeta.",
      "Los bólidos pasan directamente bordeando una colosal esfera LED interactiva de 111 metros de altura."
    ],
    streetView: {
      lat: 36.1147,
      lng: -115.1728,
      heading: 190,
      pitch: 0,
      embedUrl: "https://maps.google.com/maps?q=36.1147,-115.1728&layer=c&cbll=36.1147,-115.1728&cbp=11,190,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 70 210 L 160 210 L 280 190 L 320 130 L 260 90 L 160 90 L 90 130 Z"
  },
  {
    id: "lusail",
    name: "Lusail International Circuit",
    city: "Lusail, Doha",
    country: "Catar",
    countryCode: "QA",
    lengthKm: 5.419,
    turns: 16,
    firstGP: 2021,
    lapRecord: "1:24.319 (Max Verstappen, 2023)",
    drsZones: 1,
    trackType: "Actual / Nocturno de Alta Carga (2021-presente)",
    description: "Diseñado originariamente para MotoGP, repleto de curvas enlazadas de media y alta velocidad bajo luz artificial que provocan una fatiga física descomunal.",
    clues: [
      "Carga lateral implacable: en 2023 la FIA tuvo que imponer un límite obligatorio de 18 vueltas por juego de neumáticos por daños en las carcasas.",
      "Humedad extrema y calor asfixiante que provocó vómitos y desmayos de varios pilotos por agotamiento térmico extremo en el cockpit.",
      "Trazado con un flujo constante de curvas enlazadas en 4ª y 5ª velocidad sin casi puntos de respiro."
    ],
    streetView: {
      lat: 25.488726,
      lng: 51.451945,
      heading: 40,
      pitch: 0,
      panoId: "CAoSFkNJSE0wb2dLRUlDQWdJREd6TF8tTEE.",
      embedUrl: "https://maps.google.com/maps?q=25.488726,51.451945&layer=c&cbll=25.488726,51.451945&panoid=CAoSFkNJSE0wb2dLRUlDQWdJREd6TF8tTEE.&cbp=11,40,0,0,0&output=svembed",
      previewImage: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80"
    },
    svgPath: "M 90 200 L 170 210 L 260 170 L 300 110 L 240 70 L 160 80 L 100 120 Z"
  }
];

export const F1_TEAMS = [
  { id: "redbull", name: "Red Bull Racing", base: "Milton Keynes, UK", engine: "Honda RBPT", color: "#061389", championships: 6 },
  { id: "ferrari", name: "Scuderia Ferrari", base: "Maranello, Italia", engine: "Ferrari", color: "#e80020", championships: 16 },
  { id: "mercedes", name: "Mercedes-AMG Petronas", base: "Brackley, UK", engine: "Mercedes", color: "#00d2be", championships: 8 },
  { id: "mclaren", name: "McLaren Formula 1 Team", base: "Woking, UK", engine: "Mercedes", color: "#ff8000", championships: 8 },
  { id: "astonmartin", name: "Aston Martin Aramco", base: "Silverstone, UK", engine: "Mercedes / Honda", color: "#006f62", championships: 0 },
  { id: "williams", name: "Williams Racing", base: "Grove, UK", engine: "Mercedes", color: "#00a3e0", championships: 9 },
  { id: "alpine", name: "BWT Alpine F1 Team", base: "Enstone, UK", engine: "Renault", color: "#0078c1", championships: 2 }
];

export const COSMETICS_CATALOG = [
  { id: "avatar_helmet_gold", name: "Casco Campeón Dorado", category: "avatar", price: 350, icon: "👑", rarity: "legendary", desc: "Aura de triple campeón del mundo con visera cromada." },
  { id: "avatar_red_bull", name: "Toro de Fuego", category: "avatar", price: 180, icon: "🐂", rarity: "epic", desc: "Estilo Red Bull con tonos azul medianoche y rojo mate." },
  { id: "avatar_cavallino", name: "Tifosi Rosso Corsa", category: "avatar", price: 200, icon: "🐎", rarity: "epic", desc: "El rojo legendario de Maranello." },
  { id: "avatar_senna_brazil", name: "Tributo Ayrton '88", category: "avatar", price: 300, icon: "🇧🇷", rarity: "legendary", desc: "Verde y amarillo en homenaje al rey de la lluvia." },
  { id: "badge_lights_out", name: "Emblema Lights Out", category: "badge", price: 100, icon: "🚦", rarity: "rare", desc: "5 semáforos rojos apagándose en la recta principal." },
  { id: "badge_drs_master", name: "DRS Zone Open", category: "badge", price: 150, icon: "💨", rarity: "rare", desc: "Apertura del alerón trasero a más de 340 km/h." },
  { id: "badge_pole_position", name: "Pirelli Pole Lap", category: "badge", price: 250, icon: "⏱️", rarity: "legendary", desc: "La vuelta perfecta en Q3 en los últimos segundos." },
  { id: "border_carbon_fiber", name: "Marco Fibra de Carbono 4K", category: "frame", price: 220, icon: "🏎️", rarity: "epic", desc: "Borde texturizado con trama de tejido aeroespacial." },
  { id: "border_telemetry_neon", name: "Marco Telemetría Neón", category: "frame", price: 320, icon: "⚡", rarity: "legendary", desc: "Efecto de pulso eléctrico rojo y cian en tu tarjeta." }
];

export const RANKS = [
  { name: "Rookie F3", minPoints: 0, color: "#9ca3af", icon: "🌱" },
  { name: "F2 Contender", minPoints: 300, color: "#38bdf8", icon: "🏎️" },
  { name: "Midfield Striker", minPoints: 800, color: "#a855f7", icon: "⚡" },
  { name: "Podium Regular", minPoints: 1600, color: "#eab308", icon: "🥉" },
  { name: "Grand Prix Winner", minPoints: 2800, color: "#f97316", icon: "🏆" },
  { name: "World Champion", minPoints: 4500, color: "#ef4444", icon: "👑" },
  { name: "All-Time Legend", minPoints: 7000, color: "#f43f5e", icon: "🌟" }
];
